{% set name = "sseclient" %}
{% set version = "0.0.23" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "82a1d281b2bcb98847882069bde57a6772156f9539ddefbb78fea4f915197ec3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - requests >=2.0.0
    - six

test:
  imports:
    - sseclient

about:
  home: https://bitbucket.org/btubbs/sseclient/
  license: MIT
  # license_file: LICENSE not included in MANIFEST.in - see https://bitbucket.org/btubbs/sseclient/pull-requests/10/
  summary: 'Python client library for reading Server Sent Event streams.'
  dev_url: https://bitbucket.org/btubbs/sseclient/src

extra:
  recipe-maintainers:
    - pmlandwehr
