{% set name = "sseclient" %}
{% set version = "0.0.27" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "b2fe534dcb33b1d3faad13d60c5a7c718e28f85987f2a034ecf5ec279918c11c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - requests >=2.0.0
    - six

test:
  imports:
    - sseclient

about:
  home: https://bitbucket.org/btubbs/sseclient/
  license: MIT
  license_file: LICENSE
  # license_file: LICENSE not included in MANIFEST.in - see https://bitbucket.org/btubbs/sseclient/pull-requests/10/
  summary: Python client library for reading Server Sent Event streams.
  dev_url: https://bitbucket.org/btubbs/sseclient/src

extra:
  recipe-maintainers:
    - pmlandwehr
