{% set name = "sseclient" %}
{% set version = "0.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2fe534dcb33b1d3faad13d60c5a7c718e28f85987f2a034ecf5ec279918c11c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - requests >=2.0.0
    - six

test:
  imports:
    - sseclient
  commands:
    - pip check
  requires: 
    - pip
    - python {{ python_min }}

about:
  home: https://bitbucket.org/btubbs/sseclient/
  license: MIT
  license_file: LICENSE
  # license_file: LICENSE not included in MANIFEST.in - see https://bitbucket.org/btubbs/sseclient/pull-requests/10/
  summary: Python client library for reading Server Sent Event streams.
  dev_url: https://bitbucket.org/btubbs/sseclient/src

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
